CC=gcc
RM=rm -f

CFLAG=-g

TARGET=figure4_3
TARGET+=figure4_8
TARGET+=figure4_9
TARGET+=figure4_12
TARGET+=figure4_16
TARGET+=figure4_21
TARGET+=figure4_22
TARGET+=figure4_23
TARGET+=figure4_24
TARGET+=figure4_25
TARGET+=set_user_id

OBJECT=

all: $(TARGET) $(OBJECT);

figure4_3:figure4_3.c
	$(CC) $^ -o $@

figure4_8:figure4_8.c
	$(CC) $^ -o $@

figure4_9:figure4_9.c
	$(CC) $^ -o $@

figure4_12:figure4_12.c
	$(CC) $^ -o $@

figure4_16:figure4_16.c
	$(CC) $^ -o $@

figure4_21:figure4_21.c
	$(CC) $^ -o $@

figure4_22:figure4_22.c
	$(CC) $^ -o $@

figure4_23:figure4_23.c
	$(CC) $^ -o $@

figure4_24:figure4_24.c
	$(CC) $^ -o $@

figure4_25:figure4_25.c
	$(CC) $^ -o $@

set_user_id:set_user_id.c
	$(CC) $^ -o $@

clean:
	$(RM) $(TARGET) $(OBJECT)
