CC=gcc
CFLAGS=-g

RM=rm -f

TARGET=figure1_3
TARGET+=figure1_4
TARGET+=figure1_6
TARGET+=figure1_7
TARGET+=figure1_8
TARGET+=figure1_9
TARGET+=figure1_10

all: $(TARGET);

figure1_3: figure1_3.c
	$(CC) $(CFLAGS)  $^ -o $@ 

figure1_4: figure1_4.c
	$(CC) $(CFLAGS)  $^ -o $@ 

figure1_6: figure1_6.c
	$(CC) $(CFLAGS)  $^ -o $@ 

figure1_7: figure1_7.c
	$(CC) $(CFLAGS)  $^ -o $@ 

figure1_8: figure1_8.c
	$(CC) $(CFLAGS)  $^ -o $@ 

figure1_9: figure1_9.c
	$(CC) $(CFLAGS)  $^ -o $@ 

figure1_10: figure1_10.c
	$(CC) $(CFLAGS)  $^ -o $@ 

clean:
	$(RM) $(TARGET)
