CC=gcc
RM=rm -f

CFLAGS=-g

TARGET=figure5_4
TARGET+=figure5_5
TARGET+=figure5_7
TARGET+=figure5_8
TARGET+=figure5_9
TARGET+=figure5_10
TARGET+=figure5_11
TARGET+=figure5_12
TARGET+=figure5_13

OBJECTS=

all: $(TARGET) $(OBJECTS);

figure5_4: figure5_4.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_5: figure5_5.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_7: figure5_7.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_8: figure5_8.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_9: figure5_9.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_10: figure5_10.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_11: figure5_11.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_12: figure5_12.c
	$(CC) $(CFLAGS)  $^ -o $@

figure5_13: figure5_13.c
	$(CC) $(CFLAGS)  $^ -o $@

clean:
	$(RM) $(TARGET) $(OBJECTS)
